/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "GUIAPP_DISPLAY.h"
#include "GUIAPP_MAIN.h"
#include "sys.h"
#include "rtc.h"
#include "ff.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

WM_HWIN hWin_Display;


/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_HEADER_0 (GUI_ID_USER + 0x03)
#define ID_TEXT_0 (GUI_ID_USER + 0x05)
#define ID_TEXT_1 (GUI_ID_USER + 0x06)
#define ID_TEXT_2 (GUI_ID_USER + 0x07)
#define ID_TEXT_3 (GUI_ID_USER + 0x08)
#define ID_TEXT_4 (GUI_ID_USER + 0x09)
#define ID_TEXT_5 (GUI_ID_USER + 0x0A)
#define ID_TEXT_6 (GUI_ID_USER + 0x0B)
#define ID_TEXT_7 (GUI_ID_USER + 0x0C)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 300, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 240, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "wendu_t", ID_TEXT_0, 25, 45, 100, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "shidu_t", ID_TEXT_1, 25, 77, 100, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "dianya_t", ID_TEXT_2, 25, 109, 100, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "tcsd_t", ID_TEXT_6, 25, 141, 100, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "wendu_v", ID_TEXT_3, 127, 45, 80, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "shidu_v", ID_TEXT_4, 127, 77, 80, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "dianya_v", ID_TEXT_5, 127, 109, 80, 30, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "tcsd_v", ID_TEXT_7, 127, 141, 80, 30, 0, 0x64, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	u8 * pstr;
	u8 value_str[10];
	u8 table_value[4][20];
	u8 i;
	float dy_v; 
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00C0C0C0);
		//WINDOW_SetBkColor(hItem, 0x0085DDF3);
	
    //
    // Initialization of 'Listview'
    //
	

	
    
    //
    // Initialization of 'Header'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_HEADER_0);
    HEADER_AddItem(hItem, 240, "超声波空气湿度检测", 14);
		HEADER_SetFont(hItem, &XBF_Font);
		//HEADER_SetBkColor(hItem, 0x0014A8CD);
		
		
		

		
		
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "温度");
		TEXT_SetFont(hItem, &XBF_Font);
		TEXT_SetBkColor(hItem, 0x00E7B023);
		TEXT_SetTextColor(hItem, 0x00FFFFFF);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "湿度");
		TEXT_SetFont(hItem, &XBF_Font);
		TEXT_SetBkColor(hItem, 0x00E7B023);
		TEXT_SetTextColor(hItem, 0x00FFFFFF);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "电压");
		TEXT_SetFont(hItem, &XBF_Font);
		TEXT_SetBkColor(hItem, 0x00E7B023);
		TEXT_SetTextColor(hItem, 0x00FFFFFF);
		
		//
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "计算湿度");
		TEXT_SetFont(hItem, &XBF_Font);
		TEXT_SetBkColor(hItem, 0x00E7B023);
		TEXT_SetTextColor(hItem, 0x00FFFFFF);
		
		
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "");
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextColor(hItem, 0x00FFFFFF);
		TEXT_SetBkColor(hItem, 0x00E7B023);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "");
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
    TEXT_SetTextColor(hItem, 0x00FFFFFF);
		TEXT_SetBkColor(hItem, 0x00E7B023);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
		TEXT_SetBkColor(hItem, 0x00E7B023);
		
		//
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "");
    TEXT_SetTextColor(hItem, 0x00FFFFFF);
    TEXT_SetFont(hItem, GUI_FONT_13B_ASCII);
		TEXT_SetBkColor(hItem, 0x00E7B023);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) { 
    case ID_HEADER_0: // Notifications sent by 'Header'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;

    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
	case MSG_MEASURE_UPDATE:
			 pstr=(u8 *)pMsg->Data.p;
			 if ((pstr[0]!=':')||(pstr[1]!='V')||(pstr[2]!=' '))
			 break;
			 
			 pstr=pstr+2;
			 //更新温度
			 i=0;
			 pstr++;
			 while((*pstr!=' ')&&(*pstr!=0))
			 {
					value_str[i]=*pstr;
					i++;
					pstr++;
					if (i>9)
					break;
			 }
			 value_str[i]=0;
			 strcpy((char *)table_value[0],(char *)value_str);
			 hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
       TEXT_SetText(hItem,(const char *)value_str);
			 //更新湿度
			 i=0;
			 pstr++;
			 while((*pstr!=' ')&&(*pstr!=0))
			 {
					value_str[i]=*pstr;
					i++;
					pstr++;
					if (i>9)
					break;
			 }
			 value_str[i]=0;
			 strcpy((char *)table_value[1],(char *)value_str);
			 hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
       TEXT_SetText(hItem,(const char *)value_str);
			 //更新电压
			 i=0;
			 pstr++;
			 while((*pstr!=' ')&&(*pstr!=0))
			 {
					value_str[i]=*pstr;
					i++;
					pstr++;
					if (i>9)
					break;
			 }
			 value_str[i]=0;
			 strcpy((char *)table_value[2],(char *)value_str);
			 hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
       TEXT_SetText(hItem,(const char *)value_str);
			 
			 
			 
			 //时间
			 //sprintf((char *)table_value[3],"%04d-%02d-%02d %02d:%02d:%02d",calendar.w_year,calendar.w_month,calendar.w_date,calendar.hour,calendar.min,calendar.sec);
      	
			 dy_v=atof((const char *)value_str);
			 searchtable((char *)value_str,dy_v);
			 hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);//显示预测湿度
       TEXT_SetText(hItem,(const char *)value_str);
			 
 


		break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}



/*************************** End of file ****************************/

WM_HWIN Create_GUIAPP_DISPLAY(void) {
  WM_HWIN hWin;

  if (WM_IsWindow(hWin_Display))
  {
  	 return  hWin_Display;
  }

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, hWinMain, 0, 0);
  hWin_Display= hWin;
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/


void searchtable(char * str,float v)
{
	float shidu;
	float table_v[10]={1.5,1.010,0.922,0.860,0.818,0.789,0.765,0.700,0.700};
									  //10	20	 30	   40	    50	60	  70	  80	  90

	if (v>=table_v[0])
	{
		shidu=0.0;
	}else if ((table_v[1]<=v)&&(v<table_v[0]))//10%-20%
	{
		shidu=20-(10/(table_v[0]-table_v[1]))*(v-table_v[1]);
	}else if (((table_v[2]<=v)&&(v<table_v[1])))//20%-30%
	{
		shidu=30-(10/(table_v[1]-table_v[2]))*(v-table_v[2]);
	}else if (((table_v[3]<=v)&&(v<table_v[2])))//30%-40%
	{
		shidu=40-(10/(table_v[2]-table_v[3]))*(v-table_v[3]);
	}else if (((table_v[4]<=v)&&(v<table_v[3])))//40%-50%
	{
		shidu=50-(10/(table_v[3]-table_v[4]))*(v-table_v[4]);
	}else if (((table_v[5]<=v)&&(v<table_v[4])))//50%-60%
	{
		shidu=60-(10/(table_v[4]-table_v[5]))*(v-table_v[5]);
	}else if (((table_v[6]<=v)&&(v<table_v[5])))//60%-70%
	{
		shidu=70-(10/(table_v[5]-table_v[6]))*(v-table_v[6]);
	}else if (((table_v[7]<=v)&&(v<table_v[6])))//70%-80%
	{
		shidu=80-(10/(table_v[6]-table_v[7]))*(v-table_v[7]);
	}else 
	{
		shidu=80.0;
	}
	
	sprintf((char *)str,"%.3f%",shidu);

}
